### ISSUE TITLE
Building RMG on summit at ORNL

### ISSUE THREAD

**Issue by elbriggs** [RMGDFT/rmgdft#10]
If you don't already have the source you can obtain it using

git clone https://github.com/RMGDFT/rmgdft.git

cd to the top level directory (rmgdft) 

Set some environment variables and load the correct module stack

export FC=/sw/summit/gcc/6.4.0/bin/gfortran
export CC=/sw/summit/gcc/6.4.0/bin/gcc
export CXX=/sw/summit/gcc/6.4.0/bin/g++
module load gcc/6.4.0
module load boost
module load essl
module load cuda
module load fftw
module load cmake/3.9.2

make a build subdirectory and cd into it
mkdir build
cd build

configure the build with the following cmake command
cmake -DRMG_GPU_ENABLED=1 -DBLAS_blas_LIBRARY=/sw/summit/essl/6.1.0-2/essl/6.1/lib64/libessl.so ..

Create the rmg-gpu binary
make -j32 rmg-gpu

**Comment by elbriggs** [comment]
The recommended procedure on Summit has been changed. If you don't already have the source you can obtain it by.

git clone https://github.com/RMGDFT/rmgdft.git
then execute the following commands
cd rmgdft
mkdir build
cd build
export FC=/sw/summit/gcc/6.4.0/bin/gfortran
export CC=/sw/summit/gcc/6.4.0/bin/gcc
export CXX=/sw/summit/gcc/6.4.0/bin/g++
module load gcc/6.4.0
module load boost
module load essl
module load cuda
module load fftw
module load cmake/3.14.2
export BLA_VENDOR=IBMESSL
cmake -DRMG_GPU_ENABLED=1 -DBLAS_blas_LIBRARY=/sw/summit/essl/6.1.0-2/essl/6.1/lib64/libessl.so ..
make -j32 rmg-gpu

**Comment by elbriggs** [comment]
The recommended procedure on Summit has been changed. If you don't already have the source you can obtain it by.

git clone https://github.com/RMGDFT/rmgdft.git
then execute the following commands
cd rmgdft
mkdir build
cd build
export FC=/sw/summit/gcc/6.4.0/bin/gfortran
export CC=/sw/summit/gcc/6.4.0/bin/gcc
export CXX=/sw/summit/gcc/6.4.0/bin/g++
module load gcc/6.4.0
module load boost
module load essl
module load cuda
module load fftw
module load hdf5/1.8.18
module load cmake/3.14.2
export BLA_VENDOR=IBMESSL
cmake -DRMG_GPU_ENABLED=1 -DBLAS_blas_LIBRARY=/sw/summit/essl/6.1.0-2/essl/6.1/lib64/libessl.so ..
make -j32 rmg-gpu

If the make fails the first time try it again. Still trying to track down why this occurs.

**Comment by elbriggs** [comment]
The recommended procedure on Summit has been changed. If you don't already have the source you can obtain it by.

git clone https://github.com/RMGDFT/rmgdft.git
then execute the following commands
cd rmgdft
mkdir build
cd build
export FC=/sw/summit/gcc/6.4.0/bin/gfortran
export CC=/sw/summit/gcc/6.4.0/bin/gcc
export CXX=/sw/summit/gcc/6.4.0/bin/g++
module load gcc/6.4.0
module load boost
module load essl
module load cuda
module load fftw
module load hdf5
module load cmake/3.14.2
export BLA_VENDOR=IBMESSL
cmake -DRMG_GPU_ENABLED=1 -DBLAS_blas_LIBRARY=/sw/summit/essl/6.1.0-2/essl/6.1/lib64/libessl.so ..
make -j32 rmg-gpu

**Comment by elbriggs** [comment]
The recommended procedure on Summit has been changed. If you don't already have the source you can obtain it by.

git clone https://github.com/RMGDFT/rmgdft.git
then execute the following commands
cd rmgdft
mkdir build
cd build

export FC=/sw/summit/gcc/7.4.0/bin/gfortran
export CC=/sw/summit/gcc/7.4.0/bin/gcc
export CXX=/sw/summit/gcc/7.4.0/bin/g++
export BLA_VENDOR=IBMESSL
module load gcc/7.4.0
module load boost
module load essl
module load cuda
module load fftw
module load hdf5
module load cmake/3.18.1
module load bzip2
cmake -DRMG_CUDA_ENABLED=1 -DBLAS_blas_LIBRARY=/sw/summit/essl/6.1.0-2/essl/6.1/lib64/libessl.so ..
make -j32 rmg-gpu

**Comment by elbriggs** [comment]
The recommended procedure on Summit has been changed. If you don't already have the source you can obtain it by.

git clone https://github.com/RMGDFT/rmgdft.git
then execute the following commands
cd rmgdft
mkdir build
cd build

export FC=/sw/summit/gcc/9.1.0-alpha+20190716/bin/gfortran
export CC=/sw/summit/gcc/9.1.0-alpha+20190716/bin/gcc
export CXX=/sw/summit/gcc/9.1.0-alpha+20190716/bin/g++
export BLA_VENDOR=OpenBLAS
module load gcc
module load boost
module load openblas/0.3.15-omp
module load cuda/11.0.3
module load fftw
module load hdf5
module load cmake/3.20.2
module load bzip2
cmake -DRMG_CUDA_ENABLED=1 ..
make -j16 rmg-gpu

**Comment by dblinger** [comment]
Dear Emil,

These instructions produce compile-time errors for the current version (commit ca6fd739b73ac678cfbe5ed289fa657b18bab2f0) on Summit.  I can confirm they worked as recently as commit  351e60fc81d5025f4e31cd76abd8a35acf91cf19.

Thanks, and best,
David

**Comment by elbriggs** [comment]
Thanks for letting me know David. Fixed in latest commit to master.
Regards Emil
