### ISSUE TITLE
spglib does not work correctly for hexagonal symmetry

### ISSUE THREAD

**Issue by elbriggs** [RMGDFT/rmgdft#2]
This is an issue with the third party symmetry library used by RMG.

**Comment by prckent** [comment]
Is there a reproducer for this? Do the spglib folks know of the problem?

**Comment by elbriggs** [comment]
Yes. It was reported some time ago. I just checked and it may be fixed based on this note from version 1.13 which was recently released.

2019-07-02  Atsushi Togo  <atz.togo@gmail.com>

	* Version 1.13
	
	* src/spacegroup.c (match_hall_symbol_db_ortho, match_hall_symbol_db_monocli):

	Fix Issue#57 of SeekPath: Standardizations of choices of a,b,c axes
	for Cmma (67), Ccca(68), Ibca(73), Imma(74) were fixed. For
	monoclinic systems, lengths of non-unique axes are now checked by a
	exhaustive way.
	
	* src/kpoint.c (check_mesh_symmetry):

	Issue#79: Treatment of ir-kpoint search for special cases with three fold
	rotation (e.g., hexagonal or primitive FCC).

**Comment by WenchangLu** [comment]
symmetry and kpoint problem for hexagonal case is solved in the recent commit. Now hexagonal lattice should work with any symmetry. Testings with graphite and two Mg atoms cell agree well with QE calculations.
