### ISSUE TITLE
exact exchange and hybrid functional

### ISSUE THREAD

**Issue by WenchangLu** [RMGDFT/rmgdft#25]

**Comment by WenchangLu** [comment]
Several methods may be used to speed up the calculations and to reduce the memory requirement. Cholesky decomposition from 4 indexes to 3 indexes. Lin Lin's method ...

**Comment by elbriggs** [comment]
Exact exchange is working now for gamma with the gaupbe hybrid functional. GPU support is working as well. 
TBD
K-point support
Additional ways of handling the divergence at Q=0

**Comment by WenchangLu** [comment]
Hybrid functionals (at least gaupbe)  are working for both RMG and ON modules.

**Comment by WenchangLu** [comment]
Hybrid functionals, pbe0, hse are implemented. non-gamma points version works too now. More tests are welcome.

**Comment by WenchangLu** [comment]
Currently we only have Gygi's q=0 divergence treatment  Gygi-Baldereschi, PRB 34, 4405 (1986)
