### ISSUE TITLE
Add a feature that prints out a list of all options when --help is passed on the command line.

### ISSUE THREAD

**Issue by elbriggs** [RMGDFT/rmgdft#3]

**Comment by elbriggs** [comment]
Since the definitive list of input options is the code itself a --help option will always be up to date unlike external documentation.

**Comment by prckent** [comment]
It would be time saving to later use this option for automatically generating documentation, e.g. using a little bit of python, sphinx and eventually targeting readthedocs.

**Comment by elbriggs** [comment]
Good idea. I have it printing out the input options as shown below so it should be easy to write a script to put these into whatever format we want.

Key name:     pseudo_dir
Required:     no
Key type:     string
Description:  Directory where pseudopotentials are stored.
Default:      .
Allowed:

Key name:     start_mode
Required:     no
Key type:     string
Description:  Type of run.
Default:      LCAO Start
Allowed:      "Modified LCAO Start", "Restart TDDFT", "Start TDDFT", "Gaussian Start",
              "FIREBALL Start", "LCAO Start", "Restart From File", "Random Start",


Key name:     kohn_sham_pre_smoothing
Required:     no
Key type:     integer
Description:  Number of global grid pre-smoothing steps to perform before a multigrid preconditioner iteration.
Min value:    1
Max value:    5
Default:      2

Key name:     bravais_lattice_type
Required:     no
Key type:     string
Description:  Bravais Lattice Type.
Default:      Orthorhombic Primitive
Allowed:      "Orthorhombic Primitive", "Hexagonal Primitive", "Cubic Primitive",

Key name:     use_async_allreduce
Required:     no
Key type:     boolean
Description:  Use asynchronous allreduce if available.
Default:      true

**Comment by elbriggs** [comment]
This is pretty much functional now and the output is uploaded to the Github wiki with some manually applied formatting tweaks. Still TBD is scripts for putting it into alternate formats plus expansion of some the descriptions of each of the input options since not all of them are documented to the same level of detail.

**Comment by elbriggs** [comment]
Looking at the wiki one obvious enhancement which would enhance usability would be to group the options by section. Right now it's just done alphabetically which can put totally unrelated options next to each other.

**Comment by prckent** [comment]
Format as markdown or at least non-fixed format for the description field. On my screen some of the information is "lost" without scrolling.

**Comment by elbriggs** [comment]
I thought I could fix it with a snippet of inline css but it appears that github only allows a limited subset of css through their filters so I'll have to reformat it externally.

**Comment by elbriggs** [comment]
Looks better now (at least on my monitor). I guess I understand why github doesn't want to allow arbitrary css through the output filter but it does make formatting a little trickier.
