### ISSUE TITLE
Fortran dependencies in RMG?

### ISSUE THREAD

**Issue by prckent** [RMGDFT/rmgdft#31]
Q. What are the Fortran dependencies in RMG and can they be avoided if a Fortran compiler is simply unavailable?

Based on a `find . -name "*.f90"' I see fortran in
1. TDDFT/ELDYN. Is it possible to simply not enable the TDDFT functionality?
2. XC. These look like the XC functional routines imported from QE. When are these used vs the ones from libxc?

**Comment by elbriggs** [comment]
You are correct that the fortran dependencies are from the QE XC functional routines but the libxc dependency is actually contained in the QE routines. I don't know why the QE developers chose to do this but I suspect it is because their internal routines are quite a bit faster.

**Comment by WenchangLu** [comment]
It is possible to disable TDDFT functionality to avoid Fortran files in ELDYN.
