### ISSUE TITLE
Including dispersion

### ISSUE THREAD

**Issue by sbisbill** [RMGDFT/rmgdft#35]
Is is possible to add vdW corrections to functionals such as PBE? If so, which dispersion methods are available, and how is this specified in the input file?

**Comment by elbriggs** [comment]
RMG does support vdW corrections. There are a couple on input file options relating to it. Normally RMG will pick up the functional from the pseudopotential file. To add in vdw corrections add the following to the input file

exchange_correlation_type="vdw-df"

You also have to make sure that the vdW_kernel_table file is located in your runtime directory. This file is included in the rmg source in the XC directory. There are a couple of other options relating to vdW corrections as well. For example you can specify whether to use a fine or coarse grid to compute the corrections using the
vdwdf_grid_type="Fine"
or
vdwdf_grid_type="Coarse"
the default is Coarse and should be fine for most purposes.

**Comment by elbriggs** [comment]
Grimme D2 has also been implemented.
