### ISSUE TITLE
Are there plans to implement the stress tensor?

### ISSUE THREAD

**Issue by prckent** [RMGDFT/rmgdft#40]
To increase utilization of RMG, I think availability of a stress tensor is very important and is perhaps the most important missing feature for general applications. Are there plans to implement stress or any particular difficulties in the implementation ? The stress tensor would enable easy volume and shape relaxation in solid state calculations, plus NPT molecular dynamics. It is also a helpful check on calculations to catch mistakes such unit conversion errors that are easily made when getting started with a code.

**Comment by elbriggs** [comment]
We intend to do this but have not determined any sort of timetable for it. No conceptual difficulties just a matter of doing all of the necessary work.

**Comment by prckent** [comment]
Thanks! Does it work with self-consistent vdw? i.e. All the plumbing is there for different functionals?

**Comment by WenchangLu** [comment]
Works only for LDA now. extra terms are needed for vdw, GGA, Ultrasoft pseudopotential, LDA+U.

**Comment by prckent** [comment]
Does it abort for xc!=lda?

**Comment by WenchangLu** [comment]
No, I will put an condition to abort for stress so that we don't get confused result.

**Comment by WenchangLu** [comment]
added condition to abort for not-implemented cases.

**Comment by prckent** [comment]
We had (have) this problem in QMCPACK...

**Comment by WenchangLu** [comment]
Now stress tensor calculation and cell relax are implemented in  norm-conserving and ultrasoft, LDA and GGA. It tested with orthorhombic and hexagonal lattice. vdw-df term for stress is still missing.

**Comment by WenchangLu** [comment]
Now the code has option for LDA+U and hybrid functionals, stress terms from LDA+U and Exx should be added.
