### ISSUE TITLE
range separated functionals  for tddft

### ISSUE THREAD

**Issue by jjakowski** [RMGDFT/rmgdft#46]
The rmgdft  wiki page  https://github.com/RMGDFT/rmgdft/wiki/Input-File-Options  lists  several  functional.  Is  the liar up to date ? 

    Key name:     exchange_correlation_type
    Required:     no
    Key type:     string
    Default:      "AUTO_XC"
    Allowed:      "vdw-df-c09" "sla+pw+pbe+vdw1" "VDW-DF" "vdw-df" "gaupbe" "B3LYP"
                  "hse" "mgga tb09" "AUTO_XC" "m06l" "VDW-DF-CX" "tpss" "ev93"
                  "optbk88" "sogga" "wc" "HSE" "HCTH" "hcth" "Q2D" "q2d" "PBESOL"
                  "tb09" "b86bpbe" "PW86PBE" "PBE0" "MGGA TB09" "pw86pbe" "REVPBE"
                  "pbe" "revpbe" "GGA PBE" "BLYP" "pbe0" "pbesol" "blyp" "PBE" "GGA
                  XP CP" "pw91" "GGA XB CP" "TB09" "optb86b" "olyp" "BP" "GGA BLYP"
                  "bp" "b3lyp" "LDA" "vdw-df-cx" "PW91" "PZ" "pz"

Also, can we have use a range separated version of these functionals? 
Range separation is critical for TDDFT  as we can otherwise  drive the system into  unphysical /fringe states  due to charge transfer.  As a result  we will get wrong peaks  in  low energy.

**Comment by WenchangLu** [comment]
we adopted XC functionals from QuantumEspresso, not fully tested all of them.
