### ISSUE TITLE
  new functionality request: cube files

### ISSUE THREAD

**Issue by jjakowski** [RMGDFT/rmgdft#49]
I would  like to request adding the printing  *cube files for  visualization and postprocessing? 
This format that  we need is  used   by  many  codes  including Vesta,  VMD  etc. It is quite popular in community so   general users would appreciate. 

Here is the description: http://paulbourke.net/dataformats/cube/.
Considering that the wavefunctions and densities  are already  available on the mesh it is quite straightforward to generate the corresponding cube files. All you need it to add the header.  

I suggest that this is becomes a general functionality   got users with generic names, say  for example 

 "mo34a.cube"  -- denotes   34th orbital for spin up (alpha),
 "mo22b.cube"  -- denotes  22nd orbital for spin down (beta)
 "density.cube"  -- denotes  total charge density  on the mesh.

And in the input file, user can just  indicate  that he/she want to visualize   data and give the list of MOs. In general we may have 1000 orbitals, but want to analyze some of them. 

Jacek

**Comment by WenchangLu** [comment]
Cube format for density, Hatree potential, and wavefunctions has been implemented. 
for wavefunctions output, add line in input file
cube_states_list="0-2, 6, 8" 
this will output wavefunctions 0, 1, 2, 6, 8
