### ISSUE TITLE
wrong units in density.cube file 

### ISSUE THREAD

**Issue by jjakowski** [RMGDFT/rmgdft#55]
The  header in` density.cube` file is currently in Angstrooms.  Currently Angstrooms  is used for both atomic coordinates  and for  mesh description.  However, when  the `density.cube` is opened with  VESTA or VMD  the coordinates and  mesh is interpreted as  it is Bohrs  and all bonds seems to be compressed.  

For example,

**1) Here is the  first few lines of  "density.cube" created  by RMG:**

#This is a Cube file to be viewed
#Atomic coordinates in Angstroms
 720  0.0  0.0  0.0 1  
192     0.206710     0.000000     0.000000
192     0.000000     0.206710     0.000000
192     0.000000     0.000000     0.206710
 6  0.000000 2.697192e+01   1.944030e+01   1.011858e+01
 6  0.000000 2.587621e+01   1.906240e+01   9.511481e+00
 6  0.000000 2.523281e+01   2.013900e+01   9.136980e+00
 6  0.000000 2.593221e+01   2.117970e+01   9.509981e+00
 6  0.000000 2.700912e+01   2.074900e+01   1.011538e+01
 6  0.000000 3.238073e+01   1.892400e+01   2.118180e+01

and corresponding composite plot of structure +density:

![image](https://user-images.githubusercontent.com/6385536/75716140-9ef91900-5c9c-11ea-8775-e674af547ef8.png)

**2) Here is  how it should  look like (the  same file but  with header corrected):**

#This is a Cube file to be viewed
#Atomic coordinates in bohrs 
 720  0.0  0.0  0.0
 192     0.39062      0.000000     0.000000
 192     0.000000     0.39062      0.000000
 192     0.000000     0.000000     0.39062  
 6  0.000000    50.96953537     36.73684491     19.12134876
 6  0.000000    48.89895821     36.02271594     17.97409368
 6  0.000000    47.68310593     38.05719926     17.2663898
 6  0.000000    49.00478309     40.02384127     17.97125909
 6  0.000000    51.03983333     39.20993456     19.11530163

and corresponding composite plot of structure +density:
![image](https://user-images.githubusercontent.com/6385536/75717035-5f333100-5c9e-11ea-9e06-33f3279b110e.png)

Notice that  the first version shows  bond betnween all carbons in the  hexagons.

**Comment by WenchangLu** [comment]
fixed the bug for unit in cube files. All atoms' coordinate and dx,dy,dz are in unit of Bohr.
