### ISSUE TITLE
units for coordinates in log file

### ISSUE THREAD

**Issue by jjakowski** [RMGDFT/rmgdft#56]
RMG converts  internally    atomic coordinates from   Angstrooms to Bohr, which is  the default unit for computations.  However, it would be very useful if  the coordinates in the  original Angstroom units  were also printed along with  coordinates  in Bohr, for verification and analysis purposes. 
Also,  the  actual units  (bohr or angstrom) should be printed in the logfile to avoid confusion, for example:

Initial Ionic Positions And Displacements (Bohr)
Species      X           Y           Z           dX          dY          dZ
  C       25.3293     22.9600     29.2070      0.0000      0.0000      0.0000
  C       27.5363     22.9600     27.7857      0.0000      0.0000      0.0000
  C       23.7313     25.1732     29.2251      0.0000      0.0000      0.0000
..

**Comment by WenchangLu** [comment]
now initial atomic coordinates are printed in log file in both bohr and angstrom units.
