### ISSUE TITLE
warning: value computed is not used

### ISSUE THREAD

**Issue by frobnitzem** [RMGDFT/rmgdft#65]
Compiling produced a warning message related to increment n_count:
https://github.com/RMGDFT/rmgdft/blob/baec0e3d5d83a97796c532cae261666c8d115aa2/RMG/Common/fire.cpp#L136

src/rmgdft/RMG/Common/fire.cpp: In function ‘void fire(double*, double, double, double, int, int*)’:
src/rmgdft/RMG/Common/fire.cpp:136:9: warning: value computed is not used [-Wunused-value]
         *n_count ++;
         ^~~~~~~~~~~
Apparently, some parentheses are needed so that the value is incremented.

**Comment by elbriggs** [comment]
Thanks. Just committed a fix.
