### ISSUE TITLE
100%*** No rule to make target `../blas', needed by `rmg-cpu'.  Stop.

### ISSUE THREAD

**Issue by BobbyWangg** [RMGDFT/rmgdft#75]
I got this error when I compiled the master version.
![image](https://user-images.githubusercontent.com/108932867/177983403-8156e09e-24b5-4da8-91a0-b2c61ba5bbd5.png)
[100%] Building CXX object Interfaces/CMakeFiles/Interfaces.dir/WriteEshdf.cpp.o
[100%] Building CXX object Interfaces/CMakeFiles/Interfaces.dir/Wannier.cpp.o
[100%] Linking CXX static library libInterfaces.a
[100%] Built target Interfaces
[100%] Building CXX object RMG/CMakeFiles/rmg-cpu.dir/Common/Main.cpp.o
make[2]: *** No rule to make target `../blas', needed by `rmg-cpu'.  Stop.
make[1]: *** [RMG/CMakeFiles/rmg-cpu.dir/all] Error 2
make: *** [all] Error 2

My compiler version is：
export CC=gcc(7.3.0)
export CXX=g++(7.3.0)
export FC=mpif90(openmpi4.1.1)

My cmake command is :
cmake .. -DFFTW_LIBRARIES=/public4/soft/fftw/3.3.8-jy/lib -DFFTWF_LIBRARIES=/public4/soft/fftw/3.3.8-jy/lib -DFFTW_INCLUDES=/public4/soft/fftw/3.3.8-jy/include -DBLAS_LIBRARIES=/public4/home/sc56648/soft/rmgdft-master/blas -DLINK_LIBRARIES=libm.so  -DCMAKE_INSTALL_PREFIX=/public4/home/sc56648/soft/rmgdft-master/installmake && make install 

cmake was succeed, but when I run make ,I got the above error.
Does anyone know what's going on, please?
Thanks for any help！

**Comment by elbriggs** [comment]
Hi. What platform/distribution are you using?

**Comment by BobbyWangg** [comment]
hello,I'm using centos7.

**Comment by elbriggs** [comment]
It looks like you are trying to use a blas library located in /public4/home/sc56648/soft/rmgdft-master/blas right? Are the actual libraries located in a subdirectory of that?

**Comment by BobbyWangg** [comment]
> It looks like you are trying to use a blas library located in /public4/home/sc56648/soft/rmgdft-master/blas right? Are the actual libraries located in a subdirectory of that?

No,This directory is an empty directory.
If I don't set -DBLAS_LIBRARIES=/public4/home/sc56648/soft/rmgdft-master/blas , when I run cmake ,it will report this error: 
![image](https://user-images.githubusercontent.com/108932867/178041657-e814db40-1de4-4650-a0b2-639e661a0573.png)
CMake Error at /public4/soft/cmake/3.17.0/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
And ,if I set -DBLAS_LIBRARIES as the real blas installation path ,it will report this error:
![image](https://user-images.githubusercontent.com/108932867/178042475-37bc10c2-ae17-4e96-9c38-6eaa5f588257.png)
CMake Error at scalapack/CMakeLists.txt:284 (install):
  install FILES given directory "/public4/soft/blas/lib" to install.

"/public4/soft/blas/lib" is the blas installation path.
![image](https://user-images.githubusercontent.com/108932867/178042631-07f303b3-9777-4601-904c-75029d04b42d.png)

So,I can only set it to an empty directory .

Cloud you please tell me what is wrong with my settings?

**Comment by elbriggs** [comment]
Hmm. Not sure exactly. I haven't used Centos in a while but my recollection is that an Openblas package is available for it. Can you check if it is installed in the standard location? If so then you could remove all of the BLAS cmake options and instead try

export BLA_VENDOR=OpenBLAS

before running cmake.

**Comment by BobbyWangg** [comment]
> 



> Hmm. Not sure exactly. I haven't used Centos in a while but my recollection is that an Openblas package is available for it. Can you check if it is installed in the standard location? If so then you could remove all of the BLAS cmake options and instead try
> 
> export BLA_VENDOR=OpenBLAS
> 
> before running cmake.

I'm using HPC, so I can't install openblas in the standard location.
I try to install openblas and then export LD_LIBRARY_PATH=install path.
Thanks for your guidance

**Comment by BobbyWangg** [comment]
> export BLA_VENDOR=OpenBLAS

Thank you so much . After installing openblas I successfully solved the problem.
