### ISSUE TITLE
RMG Exx integral output

### ISSUE THREAD

**Issue by kgasperich** [RMGDFT/rmgdft#76]
@WenchangLu I've been working on the rmg->qp2 integral interface, and I noticed a few things in the afqmc output that seem incorrect.
I've attached an example input file and some of the resulting output (it should be mostly the same as the `Diamond2` test with some minor changes); I couldn't include the `afqmc_rmg.h5` because it was too large, but some of its contents are in the `dump.*` files in the attachment (from `h5ls` and `h5dump` for specific datasets).

The issues are seen in the `MinusK` array and in `Hamiltonian/KPFactorized/L[Q]`.
If the first kpt is `[0, 0, 0]`, then `MinusK` should be the same as the first column of `QKTok2` so that `kpt[i] + kpt[MinusK[i]] == 0` (see `dump.MinusK` and `dump.QKTok2` in the attachment).
Currently it looks like `MinusK` is the first row of `QKTok2` (i.e. `kpt[i] - kpt[MinusK[i]] == 0`).

For this k-point grid, there are 8 (out of 64) kpts that are their own additive inverse (0, 2, 8, 10, 32, 34, 40, 42), so those should all have some data stored in `Hamiltonian/KPFactorized/L[Q]` (I'd expect ~60 cholesky vectors for this particular input).  The first of these has only one cholesky vector, and the rest have zero (see `dump.KPFactorized_sizes` in the attachment).
For the remaining 56 kpts, they should make up 28 (Q, -Q) pairs, so only one in each pair needs to be stored; for this input, it looks like all of them are being stored (although unlike the 8 symmetric k-points, it looks like all of the data is included for these).

[exx-diamond2.tar.gz](https://github.com/RMGDFT/rmgdft/files/9074304/exx-diamond2.tar.gz)

**Comment by WenchangLu** [comment]
I will contact Kavin for specifics of this issue.

**Comment by WenchangLu** [comment]
I understand that the output is correct but has some redundent info.
