### ISSUE TITLE
Why is k-point needed for Real-space basis

### ISSUE THREAD

**Issue by m3lab-zzl** [RMGDFT/rmgdft#78]
Hi, I am not familiar with the underlying formula of DFT codes, and got confused in some conceptions. 

I know wavefunction can be expressed on the real-space basis, plane-wave, or LCAO basis.
The plane-wave code represents wavefunction in k-space though Fourier transform, thus the k-point is needed. But why does the real-space basis code still need k-space? Is it just for computational efficiency or is it a natural requirement of ALL DFT code? 

Many Thanks.

**Comment by elbriggs** [comment]
This is a conseqence of the periodic nature of the wavefunctions in a crystal. Plane waves provide a convenient way of expressing this but the concept is more fundamental than that.

**Comment by m3lab-zzl** [comment]
> This is a conseqence of the periodic nature of the wavefunctions in a crystal. Plane waves provide a convenient way of expressing this but the concept is more fundamental than that.

Thanks, I reviewed the textbook of solid physics and agree with you.
Still, I am wondering is it possible to solve the KS equation without K-point? For example, in a non-periodic system.
