### ISSUE TITLE
Compiling on Frontier

### ISSUE THREAD

**Issue by aannabe** [RMGDFT/rmgdft#89]
Hello,

I encountered an issue while trying to compile RMG on OLCF/Frontier. The compilation process fails consistently for both `develop` and `master` branches. I have attached my compile script, which I took adapted from the provided wiki page. The log of the build is attached as well.

I appreciate any insights or suggestions to resolve this issue. Thank you for your assistance!

[frontier.zip](https://github.com/RMGDFT/rmgdft/files/12457930/frontier.zip)

**Comment by elbriggs** [comment]
Hi
  I just built develop successfully on frontier using the same modules and commands but I did run into one strange issue. I got an error the first time I ran
make -j32 rmg-gpu
but I just executed the make command twice and it completed the second time. I think there may be some issue with parallel make. Can you try this and let me know if that works for you?

**Comment by aannabe** [comment]
I reran the `make` command and it indeed compiled. I tried the C60 molecule given in the tests and everything seems to be matching. Thank you.
